name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Dev tools for checks:
          pip install ruff black mypy pytest
          # Your project deps, if present:
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format)
        run: black --check .

      - name: Mypy (type check)
        run: |
          if [ -d src ]; then
            mypy src/
          else
            echo "No src/ directory yet; skipping mypy"
          fi

      - name: Pytest (tests)
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests/ directory yet; skipping pytest"
          fi
