name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest mypy

      - name: Ruff (lint)
        run: ruff check .

      - name: Pytest (tests)
        if: ${{ hashFiles('tests/**') != '' }}
        env:
          PYTHONPATH: .
        run: pytest -q

      - name: Mypy (type check)
        if: ${{ hashFiles('src/**') != '' }}
        run: mypy src
