name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Dev tools
          pip install ruff black mypy pytest
          # Project deps (optional if you have requirements.txt)
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format)
        run: black --check .

      - name: Mypy (type check)
        run: mypy src/

      - name: Pytest (tests)
        run: pytest -q
